name: Publish to AWS

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-fund

      - name: Build the app
        run: npm run build

      - name: Install AWS CLI
        run: bash .github/scripts/install-aws-cli.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ${{ vars.AWS_S3_DEFAULT_REGION }}

      - name: Upload to S3
        run: bash .github/scripts/upload-to-s3-bucket.sh -b ${{ vars.AWS_S3_BUCKET_NAME }} -s dist

      - name: Set index.html cache headers
        run: |
          set -euo pipefail
          aws s3 cp s3://${{ vars.AWS_S3_BUCKET_NAME }}/index.html s3://${{ vars.AWS_S3_BUCKET_NAME }}/index.html \
            --metadata-directive REPLACE \
            --cache-control "no-cache, max-age=0, must-revalidate" \
            --content-type "text/html"
